@startuml
hide circle

class Entry {
    FileName: string
    Title: string
    HTML: template.HTML
    Preview: template.HTML
    Time: time.Time?
}

Blog ..> Templates: instantiates
Blog ..> TLSServer: instantiates
TLSServer --> HTTPServer: wraps
Blog ..> Content: load from disk
Templates -> Content: caches HTML render of
HTTPServer --> IndexHandler
HTTPServer --> AtomHandler
HTTPServer --> PageHandler
HTTPServer --> StaticHandler
Content *--> "*" Entry

IndexHandler --> Templates: renders
PageHandler --> Templates: renders


@enduml