@startuml
hide circle

class Entry {
    FileName: string
    Title: string
    HTML: template.HTML
    Preview: template.HTML
    Time: time.Time?
}

interface WebAsset {
    MimeType(): string
    Body(): []byte
}

interface WebAssetGenerator {
}

TLSServer -> HTTPServer: wraps
HTTPServer -> CachedHandler
WebAssetGenerator .> WebAsset: <<creates>>
CachedHandler --> "*" WebAssetGenerator: "selects\nby route"
CachedHandler --> "*" WebAsset: stores
WebAssetGenerator <|--> Index
WebAssetGenerator <|--> Page
WebAssetGenerator <|--> AtomXML
WebAssetGenerator <|--> StaticFile

Index --> Templater
Page --> Templater

Index --> Entries
Page --> Entries

Entries *-> "*" Entry

CachedHandler <. FileWatcher: invalidates

@enduml