@startuml
hide circle

class Entry {
    FileName: string
    Title: string
    HTML: template.HTML
    Preview: template.HTML
    Time: time.Time?
}

interface WebAsset {
    MimeType(): string
    Body(): []byte
}

TLSServer -> HTTPServer: wraps
HTTPServer -> CachedHandler
CachedHandler *--> "*" WebAsset: stores
CachedHandler --> AssetLoader
AssetLoader ..> WebAsset: <<creates>>
WebAsset <|--> Index
WebAsset <|--> Page
WebAsset <|--> AtomXML
WebAsset <|--> StaticFile

Index ..>"*" Entry: loads/renders
Page ..> Entry: loads/renders

CachedHandler <. FileWatcher: invalidates

@enduml