@startuml
hide circle

class PageTemplate {
    FileName: string
    Title: string
    HTML: template.HTML
    Preview: template.HTML
    Time: time.Time?
}

class Entry {
    MimeType: string
    Bytes: []byte
}

TLSServer -> HTTPServer: wraps
HTTPServer -> CachedHandler
CachedHandler --> AssetLoader
CachedHandler *-> "*" Entry
AssetLoader ..> Asset: loads, based on URL, extension...
Asset <|--> Index
Asset <|--> Page
Asset <|--> Atom
Asset <|--> StaticFile
Index --> PageTemplate
Page --> PageTemplate
Entry <. Asset : returns
CachedHandler <.. AssetLoader  : invalidates entries (on file change)

@enduml