name: Security Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  zizmor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zizmorcore/zizmor-action@v1
